/**
 * @file    sched_adaptive_model.h
 * @brief   Generated Decision Tree Model for Adaptive Scheduler.
 *
 * This header contains a lightweight decision tree for runtime policy
 * selection. It can be regenerated by the Python training pipeline:
 *
 *   python scripts/export_decision_tree.py
 *
 * Current model: Hand-crafted domain-knowledge tree (initial version).
 *
 * @author  @nithingoud78 (auto-generated)
 * @date    2026-07-31
 * @version 0.1.0
 *
 * @copyright Copyright (c) 2026 SchedTiny Contributors
 *            Apache License, Version 2.0
 */

#ifndef SCHEDTINY_SCHED_ADAPTIVE_MODEL_H
#define SCHEDTINY_SCHED_ADAPTIVE_MODEL_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "sched_adaptive.h"
#include "sched_benchmark.h"

#include <stdint.h>

/**
 * @brief   Model metadata.
 */
#define SCHED_ADAPTIVE_MODEL_VERSION    "0.1.0"
#define SCHED_ADAPTIVE_MODEL_DATE       "2026-07-31"
#define SCHED_ADAPTIVE_MODEL_ACCURACY   7500 /* 75.00% estimated accuracy (bp) */
#define SCHED_ADAPTIVE_MODEL_MAX_DEPTH  6
#define SCHED_ADAPTIVE_MODEL_NUM_LEAVES 8

    /**
     * @brief   Feature importance weights (basis points, sum = 10000).
     *
     * Reflects relative importance of each feature in the decision tree.
     * Generated by the training pipeline; initial values are domain estimates.
     */
    static const uint32_t sched_adaptive_feature_importance[SCHED_ADAPTIVE_NUM_FEATURES] = {
        2000, /*  0: cpu_utilization_bp       — most important       */
        500,  /*  1: task_count               — moderate             */
        300,  /*  2: ready_queue_length       — low                  */
        800,  /*  3: avg_response_time        — important            */
        400,  /*  4: avg_waiting_time         — moderate             */
        1500, /*  5: deadline_miss_rate_bp    — very important       */
        300,  /*  6: context_switch_rate_bp   — low                  */
        200,  /*  7: idle_time                — low                  */
        200,  /*  8: busy_time                — low                  */
        300,  /*  9: fault_injection_rate_bp  — moderate             */
        200,  /* 10: recovery_success_rate_bp — low                  */
        500,  /* 11: energy_consumption       — moderate             */
        300,  /* 12: avg_power                — low                  */
        800,  /* 13: criticality_hi_count     — important            */
        1500, /* 14: hi_criticality_ratio_bp  — very important       */
        200,  /* 15: mode_switch_frequency    — low                  */
    };

    /**
     * @brief   Lookup table for fast policy selection.
     *
     * Indexed by [utilization_bucket][criticality_bucket].
     * Utilization buckets:  0=<25%, 1=25-50%, 2=50-75%, 3=75-100%
     * Criticality buckets: 0=<25%, 1=25-50%, 2=50-75%, 3=>75%
     */
    static const sched_benchmark_policy_t sched_adaptive_lookup_table[4][4] = {
        /* util\crit   <25%                 25-50%               50-75%            >75%
         */
        /* <25%  */ {SCHED_BENCHMARK_POLICY_RMS, SCHED_BENCHMARK_POLICY_RMS,
                     SCHED_BENCHMARK_POLICY_MC, SCHED_BENCHMARK_POLICY_MC},
        /* 25-50%*/
        {SCHED_BENCHMARK_POLICY_RMS, SCHED_BENCHMARK_POLICY_HPF, SCHED_BENCHMARK_POLICY_MC,
         SCHED_BENCHMARK_POLICY_MC},
        /* 50-75%*/
        {SCHED_BENCHMARK_POLICY_HPF, SCHED_BENCHMARK_POLICY_EDF, SCHED_BENCHMARK_POLICY_EDF,
         SCHED_BENCHMARK_POLICY_MC},
        /* >75% */
        {SCHED_BENCHMARK_POLICY_EDF, SCHED_BENCHMARK_POLICY_EDF, SCHED_BENCHMARK_POLICY_MC,
         SCHED_BENCHMARK_POLICY_MC},
    };

    /**
     * @brief   Decision tree inference function.
     *
     * Hand-crafted domain-knowledge tree. Will be replaced by auto-generated
     * code from scripts/export_decision_tree.py after training.
     *
     * @param   f Pointer to the feature vector.
     * @return  Recommended scheduling policy.
     */
    static inline sched_benchmark_policy_t sched_adaptive_tree_predict(
        const sched_adaptive_features_t *f)
    {
        /* Level 1: CPU utilization split */
        if (f->cpu_utilization_bp > 7500)
        {
            /* High utilization regime */
            /* Level 2: deadline miss rate */
            if (f->deadline_miss_rate_bp > 500)
            {
                /* Level 3: HI-criticality ratio */
                if (f->hi_criticality_ratio_bp > 4000)
                {
                    return SCHED_BENCHMARK_POLICY_MC;
                }
                return SCHED_BENCHMARK_POLICY_EDF;
            }
            /* Low deadline misses under high load — current policy works */
            if (f->hi_criticality_ratio_bp > 5000)
            {
                return SCHED_BENCHMARK_POLICY_MC;
            }
            return SCHED_BENCHMARK_POLICY_HPF;
        }

        if (f->cpu_utilization_bp > 5000)
        {
            /* Medium utilization regime */
            /* Level 2: criticality check */
            if (f->hi_criticality_ratio_bp > 4000)
            {
                return SCHED_BENCHMARK_POLICY_MC;
            }
            /* Level 2: deadline sensitivity */
            if (f->deadline_miss_rate_bp > 300)
            {
                return SCHED_BENCHMARK_POLICY_EDF;
            }
            return SCHED_BENCHMARK_POLICY_HPF;
        }

        /* Low utilization regime */
        /* Level 2: criticality check */
        if (f->hi_criticality_ratio_bp > 4000)
        {
            return SCHED_BENCHMARK_POLICY_MC;
        }
        /* Level 2: task count — many periodic tasks benefit from RMS */
        if (f->task_count > 5)
        {
            return SCHED_BENCHMARK_POLICY_RMS;
        }
        return SCHED_BENCHMARK_POLICY_RMS;
    }

#ifdef __cplusplus
}
#endif

#endif /* SCHEDTINY_SCHED_ADAPTIVE_MODEL_H */
