#!/usr/bin/env python3
"""
export_decision_tree.py
Generates C code for the decision tree inference model (sched_adaptive_model.h)
from a trained scikit-learn model.

Usage:
    python scripts/export_decision_tree.py \\
        --results-dir results/latest \\
        --out firmware/include/sched_adaptive_model.h
"""

import argparse
import sys
from pathlib import Path
import pickle
from datetime import datetime
from sklearn.tree import _tree


def tree_to_c_code(tree_, feature_names, target_names):
    """
    Recursively generates nested if-else C statements representing the decision tree.
    """
    tree = tree_.tree_
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree.feature
    ]

    lines = []

    def recurse(node, depth):
        indent = "    " * (depth + 2)
        if tree.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_name[node]
            threshold = int(tree.threshold[node])
            lines.append(f"{indent}if (f->{name} <= {threshold})")
            lines.append(f"{indent}{{")
            recurse(tree.children_left[node], depth + 1)
            lines.append(f"{indent}}}")
            lines.append(f"{indent}else")
            lines.append(f"{indent}{{")
            recurse(tree.children_right[node], depth + 1)
            lines.append(f"{indent}}}")
        else:
            # Leaf node
            val = tree.value[node][0]
            class_idx = val.argmax()
            class_name = target_names[class_idx]
            lines.append(f"{indent}return SCHED_BENCHMARK_POLICY_{class_name};")

    recurse(0, 0)
    return "\n".join(lines)


def generate_header(clf, features, target_names, accuracy, out_file: Path):

    date_str = datetime.now().strftime("%Y-%m-%d")
    acc_bp = int(accuracy * 10000)

    c_code = tree_to_c_code(clf, features, target_names)

    # Feature importance array
    importances = clf.feature_importances_
    importance_strs = []
    for i, f in enumerate(features):
        imp_bp = int(importances[i] * 10000)
        importance_strs.append(f"        {imp_bp}, /* {i:2d}: {f:24s} */")

    importance_arr = "\n".join(importance_strs)

    content = f"""/**
 * @file    sched_adaptive_model.h
 * @brief   Generated Decision Tree Model for Adaptive Scheduler.
 *
 * This header contains a lightweight decision tree for runtime policy
 * selection. Regenerated by scripts/export_decision_tree.py
 *
 * @author  @nithingoud78 (auto-generated)
 * @date    {date_str}
 * @version 0.1.0
 *
 * @copyright Copyright (c) 2026 SchedTiny Contributors
 *            Apache License, Version 2.0
 */

#ifndef SCHEDTINY_SCHED_ADAPTIVE_MODEL_H
#define SCHEDTINY_SCHED_ADAPTIVE_MODEL_H

#ifdef __cplusplus
extern "C"
{{
#endif

#include "sched_adaptive.h"
#include "sched_benchmark.h"

#include <stdint.h>

/**
 * @brief   Model metadata.
 */
#define SCHED_ADAPTIVE_MODEL_VERSION    "0.1.0"
#define SCHED_ADAPTIVE_MODEL_DATE       "{date_str}"
#define SCHED_ADAPTIVE_MODEL_ACCURACY   {acc_bp} /* {(accuracy * 100):.2f}% estimated accuracy */
#define SCHED_ADAPTIVE_MODEL_MAX_DEPTH  {clf.max_depth}
#define SCHED_ADAPTIVE_MODEL_NUM_LEAVES {clf.tree_.n_leaves}

    /**
     * @brief   Feature importance weights (basis points, sum = 10000).
     */
    static const uint32_t sched_adaptive_feature_importance[SCHED_ADAPTIVE_NUM_FEATURES] = {{
{importance_arr}
    }};

    /**
     * @brief   Lookup table for fast policy selection.
     *
     * Indexed by [utilization_bucket][criticality_bucket].
     * Utilization buckets:  0=<25%, 1=25-50%, 2=50-75%, 3=75-100%
     * Criticality buckets: 0=<25%, 1=25-50%, 2=50-75%, 3=>75%
     */
    static const sched_benchmark_policy_t
        sched_adaptive_lookup_table[4][4] = {{
            /* util\\crit   <25%                 25-50%               50-75%            >75%
             */
            /* <25%  */ {{SCHED_BENCHMARK_POLICY_RMS, SCHED_BENCHMARK_POLICY_RMS,
                         SCHED_BENCHMARK_POLICY_MC, SCHED_BENCHMARK_POLICY_MC}},
            /* 25-50%*/
            {{SCHED_BENCHMARK_POLICY_RMS, SCHED_BENCHMARK_POLICY_HPF,
             SCHED_BENCHMARK_POLICY_MC, SCHED_BENCHMARK_POLICY_MC}},
            /* 50-75%*/
            {{SCHED_BENCHMARK_POLICY_HPF, SCHED_BENCHMARK_POLICY_EDF,
             SCHED_BENCHMARK_POLICY_EDF, SCHED_BENCHMARK_POLICY_MC}},
            /* >75% */
            {{SCHED_BENCHMARK_POLICY_EDF, SCHED_BENCHMARK_POLICY_EDF,
             SCHED_BENCHMARK_POLICY_MC, SCHED_BENCHMARK_POLICY_MC}},
    }};

    /**
     * @brief   Decision tree inference function.
     *
     * Auto-generated from scikit-learn model.
     *
     * @param   f Pointer to the feature vector.
     * @return  Recommended scheduling policy.
     */
    static inline sched_benchmark_policy_t
    sched_adaptive_tree_predict(const sched_adaptive_features_t *f)
    {{
{c_code}
    }}

#ifdef __cplusplus
}}
#endif

#endif /* SCHEDTINY_SCHED_ADAPTIVE_MODEL_H */
"""
    with open(out_file, "w") as f:
        f.write(content)

    print(f"Successfully wrote generated C header to {out_file}")


def main():
    parser = argparse.ArgumentParser(description="Export Trained Model to C Header")
    parser.add_argument(
        "--results-dir", type=str, required=True, help="Path to results directory"
    )
    parser.add_argument(
        "--out", type=str, required=True, help="Path to output header file"
    )
    args = parser.parse_args()

    model_path = Path(args.results_dir) / "adaptive_model.pkl"
    if not model_path.exists():
        print(
            f"Error: Model not found at {model_path}. Run train_scheduler_model.py first."
        )
        sys.exit(1)

    with open(model_path, "rb") as f:
        model_data = pickle.load(f)

    clf = model_data["clf"]
    features = model_data["features"]
    target_names = model_data["target_names"]
    accuracy = model_data["accuracy"]

    out_file = Path(args.out)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    generate_header(clf, features, target_names, accuracy, out_file)

    print(
        "\nNext step: Rebuild firmware to include the new model and run clang-format."
    )


if __name__ == "__main__":
    main()
